-- === Insert Customers (without id, auto-generated) ===
INSERT INTO customer (name, email) VALUES ('Alice Johnson', 'alice.johnson@example.com');
INSERT INTO customer (name, email) VALUES ('Bob Smith', 'bob.smith@example.com');

-- Insert Products without ID (auto-generated)
INSERT INTO product (product_name, category, subcategory, product_type, price, stock_quantity) VALUES
-- ELECTRONICS (8 products)
('IPHONE', 'ELECTRONICS', 'SMARTPHONES', 'PHONE', 1299.99, 25),
('SAMSUNG GALAXY', 'ELECTRONICS', 'SMARTPHONES', 'PHONE', 1199.99, 20),
('MACBOOK', 'ELECTRONICS', 'LAPTOPS', 'LAPTOP', 999.99, 15),
('IPAD', 'ELECTRONICS', 'TABLETS', 'TABLET', 1099.99, 18),
('DELL LAPTOP', 'ELECTRONICS', 'LAPTOPS', 'LAPTOP', 1399.99, 10),
('SONY HEADPHONES', 'ELECTRONICS', 'AUDIO', 'HEADPHONES', 349.99, 30),
('PIXEL', 'ELECTRONICS', 'SMARTPHONES', 'PHONE', 899.99, 22),
('BOSE EARBUDS', 'ELECTRONICS', 'AUDIO', 'EARBUDS', 299.99, 35),

-- BOOKS (7 products)
('CLEAN CODE', 'BOOKS', 'PROGRAMMING', 'BOOK', 49.99, 40),
('EFFECTIVE JAVA', 'BOOKS', 'PROGRAMMING', 'BOOK', 59.99, 30),
('THE PRAGMATIC PROGRAMMER', 'BOOKS', 'PROGRAMMING', 'BOOK', 39.99, 25),
('HARRY POTTER', 'BOOKS', 'FANTASY', 'BOOK', 19.99, 50),
('ATOMIC HABITS', 'BOOKS', 'SELF-HELP', 'BOOK', 21.99, 40),
('DEEP WORK', 'BOOKS', 'PRODUCTIVITY', 'BOOK', 18.99, 45),
('THE HOBBIT', 'BOOKS', 'FANTASY', 'BOOK', 22.99, 28),

-- HOME & KITCHEN (5 products)
('INSTANT POT', 'HOME & KITCHEN', 'APPLIANCES', 'PRESSURE COOKER', 89.99, 12),
('DYSON VACUUM', 'HOME & KITCHEN', 'APPLIANCES', 'VACUUM', 599.99, 8),
('AIR FRYER', 'HOME & KITCHEN', 'APPLIANCES', 'AIR FRYER', 119.99, 14),
('SOFA SET', 'HOME & KITCHEN', 'FURNITURE', 'SOFA', 999.99, 4),
('STANDING DESK', 'HOME & KITCHEN', 'FURNITURE', 'DESK', 299.99, 6),

-- FASHION (5 products)
('LEATHER JACKET', 'FASHION', 'MEN', 'JACKET', 129.99, 10),
('TRENCH COAT', 'FASHION', 'WOMEN', 'COAT', 149.99, 12),
('HOODIE', 'FASHION', 'UNISEX', 'SWEATSHIRT', 59.99, 20),
('RUNNING SHOES', 'FASHION', 'FOOTWEAR', 'SHOES', 89.99, 18),
('FORMAL SHIRT', 'FASHION', 'MEN', 'SHIRT', 49.99, 25),

-- TOYS (5 products)
('LEGO STAR WARS', 'TOYS', 'BUILDING SETS', 'LEGO', 129.99, 14),
('BARBIE DREAMHOUSE', 'TOYS', 'DOLLS', 'PLAYSET', 179.99, 9),
('RC CAR', 'TOYS', 'VEHICLES', 'REMOTE CONTROL', 69.99, 20),
('NERF BLASTER', 'TOYS', 'GUNS', 'BLASTER', 39.99, 30),
('BOARD GAME', 'TOYS', 'BOARD GAMES', 'GAME', 44.99, 18),

-- SPORTS (5 products)
('BASKETBALL', 'SPORTS', 'BALL', 'BALL', 29.99, 15),
('TENNIS RACKET', 'SPORTS', 'EQUIPMENT', 'RACKET', 79.99, 10),
('RUNNING TIGHTS', 'SPORTS', 'CLOTHING', 'PANTS', 49.99, 20),
('YOGA MAT', 'SPORTS', 'ACCESSORIES', 'MAT', 19.99, 25),
('FITNESS TRACKER', 'SPORTS', 'ELECTRONICS', 'TRACKER', 149.99, 12),

-- BEAUTY (5 products)
('MOISTURIZER CREAM', 'BEAUTY', 'SKIN CARE', 'CREAM', 24.99, 50),
('HAIR DRYER', 'BEAUTY', 'HAIR CARE', 'APPLIANCE', 39.99, 18),
('LIPSTICK SET', 'BEAUTY', 'MAKEUP', 'LIPSTICK', 29.99, 40),
('PERFUME', 'BEAUTY', 'FRAGRANCE', 'PERFUME', 69.99, 22),
('EYELINER', 'BEAUTY', 'MAKEUP', 'EYELINER', 14.99, 33);
